import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { handleApiRequest } from './apiHandler.js';
const app=express();
app.use(express.json({limit:'20kb'}));
app.use(handleApiRequest);
const dist=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../dist');
app.use(express.static(dist));
app.get('*',(req,res,next)=>req.path.startsWith('/api/') ? next() : res.sendFile(path.join(dist,'index.html')));
app.listen(process.env.PORT || 3001,()=>console.log('Study tracker backend ready'));
